// Chatbot Support System - Fully Powered by Gemini AI (2026)
// All responses generated by Google Gemini with real store data context
// Includes integrated Live Support Chat

// Conversation history for multi-turn context
let conversationHistory = [];

async function getChatbotResponse(message) {
    try {
        // Send to Gemini API with full conversation history
        const response = await fetch('includes/gemini_api.php', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ 
                message: message,
                history: conversationHistory
            })
        });

        const data = await response.json();
        
        if (data.success && data.message) {
            // Store conversation turn for context
            conversationHistory.push({ role: 'user', text: message });
            conversationHistory.push({ role: 'model', text: data.message });
            
            // Keep history manageable (last 20 messages)
            if (conversationHistory.length > 20) {
                conversationHistory = conversationHistory.slice(-20);
            }
            
            return data.message;
        } else {
            console.error('Gemini API Error:', data.error);
            return "⚠️ I'm having trouble connecting right now. Please try again in a moment, or contact us at support@threadpresshub.com for immediate help.";
        }
    } catch (error) {
        console.error('Connection Error:', error);
        return "⚠️ Connection issue. Please check your internet and try again, or reach us at support@threadpresshub.com.";
    }
}

// ==========================================
// SUPPORT CHAT (Integrated in widget)
// ==========================================
const SupportWidget = {
    ajaxUrl: 'includes/support-chat-ajax.php',
    pollTimer: null,
    pollInterval: 4000,
    activeConversationId: null,
    lastMessageId: 0,
    isSending: false,
    conversations: [],

    init() {
        const tabAI = document.getElementById('tab-ai');
        const tabSupport = document.getElementById('tab-support');
        if (!tabAI || !tabSupport) return;

        tabAI.addEventListener('click', () => this.switchTab('ai'));
        tabSupport.addEventListener('click', () => this.switchTab('support'));

        // New conversation buttons
        const btnNew = document.getElementById('btn-new-conversation');
        if (btnNew) btnNew.addEventListener('click', () => this.showNewConvForm());

        const btnBack = document.getElementById('btn-back-to-list');
        if (btnBack) btnBack.addEventListener('click', () => this.showConvList());

        const btnBackConvs = document.getElementById('btn-back-to-convs');
        if (btnBackConvs) btnBackConvs.addEventListener('click', () => {
            this.stopPolling();
            this.activeConversationId = null;
            this.showConvList();
        });

        // New conversation form
        const newConvForm = document.getElementById('new-conv-form');
        if (newConvForm) newConvForm.addEventListener('submit', (e) => this.createConversation(e));

        // Support send
        const sendBtn = document.getElementById('support-send');
        const input = document.getElementById('support-input');
        if (sendBtn) sendBtn.addEventListener('click', () => this.sendSupportMessage());
        if (input) input.addEventListener('keypress', (e) => {
            if (e.key === 'Enter') this.sendSupportMessage();
        });

        // Image upload
        const imgInput = document.getElementById('support-image-input');
        const removeImg = document.getElementById('support-remove-img');
        if (imgInput) imgInput.addEventListener('change', () => this.handleImageSelect());
        if (removeImg) removeImg.addEventListener('click', () => this.clearImagePreview());

        // Check unread count periodically
        this.checkUnread();
        setInterval(() => this.checkUnread(), 15000);
    },

    switchTab(tab) {
        const tabAI = document.getElementById('tab-ai');
        const tabSupport = document.getElementById('tab-support');
        const panelAI = document.getElementById('panel-ai');
        const panelSupport = document.getElementById('panel-support');
        const headerAvatar = document.getElementById('chat-header-avatar');
        const headerTitle = document.getElementById('chat-header-title');
        const headerSubtitle = document.getElementById('chat-header-subtitle');
        const footerNote = document.getElementById('chat-footer-note');

        if (tab === 'ai') {
            tabAI.classList.add('active');
            tabSupport.classList.remove('active');
            panelAI.classList.add('active');
            panelSupport.classList.remove('active');
            headerAvatar.innerHTML = '<i class="fas fa-robot"></i>';
            headerTitle.innerHTML = 'AI Assistant <span class="chat-header-badge">Gemini</span>';
            headerSubtitle.textContent = 'Powered by Google AI';
            footerNote.textContent = 'Powered by Google Gemini AI';
            this.stopPolling();
        } else {
            tabAI.classList.remove('active');
            tabSupport.classList.add('active');
            panelAI.classList.remove('active');
            panelSupport.classList.add('active');
            headerAvatar.innerHTML = '<i class="fas fa-headset"></i>';
            headerTitle.innerHTML = 'Live Support';
            headerSubtitle.textContent = 'Chat with our team';
            footerNote.textContent = 'Thread & Press Hub Support';
            this.loadConversations();
        }
    },

    async loadConversations() {
        const container = document.getElementById('support-conversations');
        container.innerHTML = '<div class="support-widget-loading"><i class="fas fa-spinner fa-spin"></i> Loading...</div>';

        try {
            const res = await fetch(this.ajaxUrl + '?action=get_conversations');
            const data = await res.json();
            if (data.success) {
                this.conversations = data.conversations;
                this.renderConversations();
            } else {
                container.innerHTML = '<div class="support-widget-empty">Unable to load conversations.</div>';
            }
        } catch (e) {
            container.innerHTML = '<div class="support-widget-empty">Connection error.</div>';
        }
    },

    renderConversations() {
        const container = document.getElementById('support-conversations');
        if (this.conversations.length === 0) {
            container.innerHTML = `
                <div class="support-widget-empty">
                    <i class="fas fa-comments" style="font-size:2rem;color:var(--text-light);"></i>
                    <p>No conversations yet.<br>Start one below!</p>
                </div>`;
            return;
        }

        container.innerHTML = this.conversations.map(conv => `
            <div class="support-widget-conv-item" data-conv-id="${conv.id}">
                <div class="support-widget-conv-top">
                    <span class="support-widget-conv-subject">${this.escapeHtml(conv.subject)}</span>
                    <span class="badge bg-${conv.status === 'open' ? 'success' : 'secondary'}" style="font-size:0.6rem;">${conv.status}</span>
                </div>
                <div class="support-widget-conv-preview">${this.escapeHtml((conv.last_message || 'No messages').substring(0, 50))}${(conv.last_message || '').length > 50 ? '...' : ''}</div>
                <div class="support-widget-conv-meta">
                    <span>${conv.last_message_at ? this.formatTime(conv.last_message_at) : ''}</span>
                    ${conv.unread_count > 0 ? `<span class="badge bg-danger" style="font-size:0.6rem;">${conv.unread_count}</span>` : ''}
                </div>
            </div>
        `).join('');

        // Click handlers
        container.querySelectorAll('.support-widget-conv-item').forEach(item => {
            item.addEventListener('click', () => {
                const id = parseInt(item.getAttribute('data-conv-id'));
                this.openConversation(id);
            });
        });
    },

    showConvList() {
        document.getElementById('support-conv-list').style.display = '';
        document.getElementById('support-new-conv').style.display = 'none';
        document.getElementById('support-chat-view').style.display = 'none';
        this.loadConversations();
    },

    showNewConvForm() {
        document.getElementById('support-conv-list').style.display = 'none';
        document.getElementById('support-new-conv').style.display = '';
        document.getElementById('support-chat-view').style.display = 'none';
    },

    async createConversation(e) {
        e.preventDefault();
        const form = e.target;
        const subject = form.querySelector('[name="subject"]').value.trim();
        const message = form.querySelector('[name="message"]').value.trim();
        if (!subject || !message) return;

        const formData = new FormData();
        formData.append('action', 'create_conversation');
        formData.append('subject', subject);
        formData.append('message', message);

        try {
            const res = await fetch(this.ajaxUrl, { method: 'POST', body: formData });
            const data = await res.json();
            if (data.success) {
                form.reset();
                this.openConversation(data.conversation_id);
            } else {
                alert(data.error || 'Failed to create conversation');
            }
        } catch (e) {
            alert('Connection error. Please try again.');
        }
    },

    async openConversation(convId) {
        this.activeConversationId = convId;
        this.lastMessageId = 0;

        document.getElementById('support-conv-list').style.display = 'none';
        document.getElementById('support-new-conv').style.display = 'none';
        document.getElementById('support-chat-view').style.display = '';

        const conv = this.conversations.find(c => c.id === convId);
        document.getElementById('support-chat-subject').textContent = conv ? conv.subject : 'Conversation';
        
        const statusBadge = document.getElementById('support-chat-status');
        const isOpen = conv && conv.status === 'open';
        statusBadge.textContent = conv ? conv.status : '';
        statusBadge.className = 'badge bg-' + (isOpen ? 'success' : 'secondary');

        // Show/hide input based on status
        document.getElementById('support-input-area').style.display = isOpen ? '' : 'none';
        document.getElementById('support-closed-msg').style.display = isOpen ? 'none' : '';

        const messagesDiv = document.getElementById('support-chat-messages');
        messagesDiv.innerHTML = '<div class="support-widget-loading"><i class="fas fa-spinner fa-spin"></i> Loading messages...</div>';

        try {
            const res = await fetch(this.ajaxUrl + '?action=get_messages&conversation_id=' + convId + '&last_id=0');
            const data = await res.json();
            messagesDiv.innerHTML = '';

            if (data.success && data.messages.length > 0) {
                data.messages.forEach(msg => {
                    this.appendSupportMessage(msg);
                    if (msg.id > this.lastMessageId) this.lastMessageId = msg.id;
                });
            } else {
                messagesDiv.innerHTML = '<div class="chat-message bot-message">Conversation started. An admin will respond soon.</div>';
            }
            messagesDiv.scrollTop = messagesDiv.scrollHeight;
        } catch (e) {
            messagesDiv.innerHTML = '<div class="support-widget-empty">Error loading messages.</div>';
        }

        // Start polling for new messages
        if (isOpen) this.startPolling();
    },

    appendSupportMessage(msg) {
        const messagesDiv = document.getElementById('support-chat-messages');
        const div = document.createElement('div');
        const isUser = msg.sender_type === 'user';
        div.className = 'chat-message ' + (isUser ? 'user-message' : 'bot-message');
        div.setAttribute('data-msg-id', msg.id);

        let content = '';
        if (msg.sender_type === 'admin') {
            content += '<div style="font-size:0.65rem;opacity:0.7;margin-bottom:2px;"><i class="fas fa-user-shield"></i> ' + this.escapeHtml(msg.sender_name) + ' <span class="badge bg-primary" style="font-size:0.55rem;">Admin</span></div>';
        }
        if (msg.image_path) {
            content += '<div style="margin-bottom:4px;"><img src="' + this.escapeHtml(msg.image_path) + '" style="max-width:100%;border-radius:6px;cursor:pointer;" onclick="window.open(this.src,\'_blank\')" alt="Image"></div>';
        }
        if (msg.message) {
            content += this.escapeHtml(msg.message).replace(/\n/g, '<br>');
        }
        content += '<div style="font-size:0.6rem;opacity:0.6;margin-top:3px;">' + (msg.created_at_formatted || msg.created_at || '') + '</div>';

        div.innerHTML = content;
        messagesDiv.appendChild(div);
        messagesDiv.scrollTop = messagesDiv.scrollHeight;
    },

    async sendSupportMessage() {
        if (this.isSending || !this.activeConversationId) return;
        const input = document.getElementById('support-input');
        const imgInput = document.getElementById('support-image-input');
        const message = input.value.trim();
        const hasImage = imgInput && imgInput.files.length > 0;

        if (!message && !hasImage) return;

        this.isSending = true;
        input.value = '';

        const formData = new FormData();
        formData.append('action', 'send_message');
        formData.append('conversation_id', this.activeConversationId);
        formData.append('message', message);

        if (hasImage) {
            formData.append('image', imgInput.files[0]);
        }

        try {
            const res = await fetch(this.ajaxUrl, { method: 'POST', body: formData });
            const data = await res.json();
            if (data.success) {
                this.appendSupportMessage(data.message);
                if (data.message.id > this.lastMessageId) this.lastMessageId = data.message.id;
                this.clearImagePreview();
            } else {
                alert(data.error || 'Failed to send');
            }
        } catch (e) {
            alert('Connection error.');
        }
        this.isSending = false;
        input.focus();
    },

    handleImageSelect() {
        const imgInput = document.getElementById('support-image-input');
        const file = imgInput.files[0];
        if (!file) return;

        const allowed = ['image/jpeg', 'image/png', 'image/gif', 'image/webp'];
        if (!allowed.includes(file.type)) {
            alert('Invalid file type. Only JPEG, PNG, GIF, WebP are allowed.');
            imgInput.value = '';
            return;
        }
        if (file.size > 5 * 1024 * 1024) {
            alert('File too large. Maximum 5MB allowed.');
            imgInput.value = '';
            return;
        }

        const reader = new FileReader();
        reader.onload = (e) => {
            document.getElementById('support-preview-img').src = e.target.result;
            document.getElementById('support-img-preview').style.display = 'flex';
        };
        reader.readAsDataURL(file);
    },

    clearImagePreview() {
        const imgInput = document.getElementById('support-image-input');
        if (imgInput) imgInput.value = '';
        const preview = document.getElementById('support-img-preview');
        if (preview) preview.style.display = 'none';
        const previewImg = document.getElementById('support-preview-img');
        if (previewImg) previewImg.src = '';
    },

    startPolling() {
        this.stopPolling();
        this.pollTimer = setInterval(() => this.fetchNewMessages(), this.pollInterval);
    },

    stopPolling() {
        if (this.pollTimer) {
            clearInterval(this.pollTimer);
            this.pollTimer = null;
        }
    },

    async fetchNewMessages() {
        if (!this.activeConversationId) return;
        try {
            const res = await fetch(this.ajaxUrl + '?action=get_messages&conversation_id=' + this.activeConversationId + '&last_id=' + this.lastMessageId);
            const data = await res.json();
            if (data.success && data.messages.length > 0) {
                data.messages.forEach(msg => {
                    if (msg.id > this.lastMessageId) {
                        const existing = document.querySelector('#support-chat-messages [data-msg-id="' + msg.id + '"]');
                        if (!existing) this.appendSupportMessage(msg);
                        this.lastMessageId = msg.id;
                    }
                });
            }
        } catch (e) {}
    },

    async checkUnread() {
        try {
            const res = await fetch(this.ajaxUrl + '?action=get_unread_count');
            const data = await res.json();
            const badge = document.getElementById('support-unread-badge');
            if (badge && data.success) {
                if (data.count > 0) {
                    badge.textContent = data.count;
                    badge.style.display = '';
                } else {
                    badge.style.display = 'none';
                }
            }
        } catch (e) {}
    },

    formatTime(dateStr) {
        if (!dateStr) return '';
        const d = new Date(dateStr);
        const months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
        let h = d.getHours();
        const ampm = h >= 12 ? 'PM' : 'AM';
        h = h % 12 || 12;
        const min = d.getMinutes().toString().padStart(2, '0');
        return months[d.getMonth()] + ' ' + d.getDate() + ', ' + h + ':' + min + ' ' + ampm;
    },

    escapeHtml(str) {
        if (!str) return '';
        const div = document.createElement('div');
        div.textContent = str;
        return div.innerHTML;
    }
};

function initChatbot() {
    const chatWidget = document.getElementById('chatbot-widget');
    const chatMessages = document.getElementById('chat-messages');
    const chatInput = document.getElementById('chat-input');
    const sendBtn = document.getElementById('chat-send');
    const toggleBtn = document.getElementById('chatbot-toggle');
    const closeBtn = document.getElementById('chat-close');
    
    // If user is not logged in, chat elements won't exist — only toggle/close work
    if (!chatInput || !sendBtn || !chatMessages) {
        if (toggleBtn) {
            toggleBtn.addEventListener('click', function() {
                chatWidget.classList.toggle('active');
            });
        }
        if (closeBtn) {
            closeBtn.addEventListener('click', function() {
                chatWidget.classList.remove('active');
            });
        }
        return;
    }
    
    // Toggle chat window
    toggleBtn.addEventListener('click', function() {
        chatWidget.classList.toggle('active');
        if (chatWidget.classList.contains('active')) {
            chatInput.focus();
        }
    });
    
    // Close chat
    closeBtn.addEventListener('click', function() {
        chatWidget.classList.remove('active');
    });
    
    // Send message on button click
    sendBtn.addEventListener('click', sendMessage);
    
    // Send message on Enter key
    chatInput.addEventListener('keypress', function(e) {
        if (e.key === 'Enter') {
            sendMessage();
        }
    });
    
    async function sendMessage() {
        const message = chatInput.value.trim();
        if (message === '') return;
        
        // Add user message
        addUserMessage(message);
        chatInput.value = '';
        chatInput.disabled = true;
        sendBtn.disabled = true;
        
        // Show typing indicator
        addTypingIndicator();
        
        // Get response from Gemini
        const response = await getChatbotResponse(message);
        
        // Remove typing indicator
        removeTypingIndicator();
        
        // Add bot response
        addBotMessage(response);
        
        // Re-enable input
        chatInput.disabled = false;
        sendBtn.disabled = false;
        chatInput.focus();
    }
    
    function addUserMessage(message) {
        const msgDiv = document.createElement('div');
        msgDiv.className = 'chat-message user-message';
        msgDiv.textContent = message;
        chatMessages.appendChild(msgDiv);
        chatMessages.scrollTop = chatMessages.scrollHeight;
    }
    
    function addBotMessage(message) {
        const msgDiv = document.createElement('div');
        msgDiv.className = 'chat-message bot-message';
        // Support markdown-like formatting
        let formatted = message
            .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
            .replace(/\*(.*?)\*/g, '<em>$1</em>')
            .replace(/\n/g, '<br>');
        msgDiv.innerHTML = formatted;
        chatMessages.appendChild(msgDiv);
        chatMessages.scrollTop = chatMessages.scrollHeight;
    }
    
    function addTypingIndicator() {
        const msgDiv = document.createElement('div');
        msgDiv.className = 'chat-message bot-message typing-indicator';
        msgDiv.id = 'typing-indicator';
        msgDiv.innerHTML = '<span></span><span></span><span></span>';
        chatMessages.appendChild(msgDiv);
        chatMessages.scrollTop = chatMessages.scrollHeight;
    }
    
    function removeTypingIndicator() {
        const indicator = document.getElementById('typing-indicator');
        if (indicator) {
            indicator.remove();
        }
    }

    // Initialize Support Widget
    SupportWidget.init();
}

// Initialize chatbot when DOM is ready
if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initChatbot);
} else {
    initChatbot();
}
