[phases.setup]
nixPkgs = ["php83Extensions.mysqli", "php83Extensions.mbstring", "php83Extensions.curl", "php83Extensions.openssl"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php -S 0.0.0.0:${PORT:-8080} -t /app"
